---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: k8s-prometheus-micrometer-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      name: example-app
  template:
    metadata:
      labels:
        name: example-app
    spec:
      containers:
        - name: example-app
          image: alexandreroman/k8s-prometheus-micrometer-demo
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
