---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: k8s-prometheus-micrometer-demo
  labels:
    name: example-app
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30011
  selector:
    name: example-app
#metricsBindAddress: 127.0.0.1:10249